// Generated by Selenium IDE
const { Builder, By, Key, until } = require("selenium-webdriver");
const assert = require("assert");

describe("Checklist", function () {
  this.timeout(30000);
  let driver;
  let vars;
  beforeEach(async function () {
    driver = await new Builder().forBrowser("chrome").build();
    vars = {};
  });
  afterEach(async function () {
    await driver.quit();
  });

  it("Deve adicionar, marcar, excluir tarefas e validar o toast", async function () {
    await driver.get("https://elisirons.github.io/checklist/");
    await driver.manage().window().setRect({ width: 1552, height: 840 });

    //Ligar a música
    await driver.findElement(By.css(".music-control")).click();

    //Tentar adicionar tarefa curta e validar o toast
    await driver.findElement(By.id("task-title-input")).sendKeys("oi");
    await driver.findElement(By.id("add-task-button")).click();

    //Espera para verificar o toast de erro
    const toast = await driver.findElement(By.css(".toast"));
    await driver.wait(until.elementIsVisible(toast), 5000);
    const toastText = await toast.getText();
    assert.strictEqual(
      toastText,
      "Sua tarefa precisa ter pelo menos 3 caracteres"
    );

    //Adicionar tarefa
    await driver.findElement(By.id("task-title-input")).clear();
    await driver
      .findElement(By.id("task-title-input"))
      .sendKeys("Levar o lixo para fora");
    await driver.findElement(By.id("add-task-button")).click();

    //Adicionar outra tarefa
    await driver.findElement(By.id("task-title-input")).clear();
    await driver.findElement(By.id("task-title-input")).sendKeys("Fazer café");
    await driver.findElement(By.id("add-task-button")).click();

    //Marcar primeira tarefa como concluída
    await driver.findElement(By.css("li:nth-child(1) > input")).click();

    //Excluir a primeira tarefa
    await driver.findElement(By.css("li:nth-child(1) > button")).click();

    //Desligar a música
    await driver.findElement(By.css(".music-control")).click();

    await driver.close();
  });
});
